# Generated by Django 4.2.29 on 2026-03-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_subsystems', to='missions.mission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('ICD', 'ICD'), ('Manual', 'User Manual'), ('Guide', 'Guide'), ('Reference', 'Reference')], default='Reference', max_length=40)),
                ('section', models.CharField(blank=True, help_text='Section or topic within the document', max_length=200)),
                ('version', models.CharField(blank=True, help_text='Document version (e.g. v2.1)', max_length=40)),
                ('location', models.CharField(help_text='Link or path to the document (SharePoint, Git repo, internal drive, PDF, etc.)', max_length=500)),
                ('user_notes', models.TextField(blank=True, help_text='Operator or engineer notes for operational context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_entries', to='missions.mission')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_entries', to='references.subsystem')),
            ],
            options={
                'verbose_name_plural': 'reference entries',
                'ordering': ['subsystem__name', 'title'],
                'indexes': [models.Index(fields=['subsystem'], name='references__subsyst_4747db_idx'), models.Index(fields=['document_type'], name='references__documen_aeffd9_idx'), models.Index(fields=['title'], name='references__title_ddb56c_idx')],
            },
        ),
    ]
