# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceentry',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_entries', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_subsystems', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
