# Generated by Django 4.2.29 on 2026-03-07 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedures', '0004_add_procedure_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subsystem', models.CharField(choices=[('ADCS', 'ADCS'), ('POWER', 'Power'), ('COMM', 'Comm'), ('PAYLOAD', 'Payload'), ('CDH', 'C&DH'), ('THERMAL', 'Thermal'), ('PROPULSION', 'Propulsion'), ('GNC', 'GNC'), ('GROUND', 'Ground'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('severity', models.CharField(choices=[('L1', 'L1 — Informational'), ('L2', 'L2 — Minor'), ('L3', 'L3 — Operational'), ('L4', 'L4 — Major'), ('L5', 'L5 — Critical')], default='L2', max_length=5)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('MITIGATED', 'Mitigated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('detected_time', models.DateTimeField()),
                ('root_cause', models.TextField(blank=True, help_text='Root cause summary documented at resolution.')),
                ('resolution_actions', models.TextField(blank=True, help_text='Actions taken to resolve the issue.')),
                ('recommendations', models.TextField(blank=True, help_text='Follow-up recommendations or lessons learned.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='procedures.satellite')),
            ],
            options={
                'ordering': ['-detected_time'],
            },
        ),
        migrations.CreateModel(
            name='EventTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('NOTE', 'Note'), ('STATUS_CHANGE', 'Status Change'), ('SEVERITY_CHANGE', 'Severity Change'), ('ACTION', 'Action Taken'), ('PROCEDURE', 'Procedure Run')], default='NOTE', max_length=20)),
                ('body', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=50)),
                ('new_value', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
