# Generated by Django 6.0.3 on 2026-03-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0003_add_run_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FDIREntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fault name', max_length=200)),
                ('fault_code', models.CharField(blank=True, help_text='Short identifier or code', max_length=80)),
                ('severity', models.CharField(blank=True, choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('fault_type', models.CharField(blank=True, max_length=80)),
                ('triggering_conditions', models.TextField(blank=True, help_text='When/how the fault is detected')),
                ('detection_thresholds', models.TextField(blank=True, help_text='Thresholds or criteria')),
                ('onboard_automated_response', models.TextField(blank=True, help_text='What the spacecraft does automatically')),
                ('version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator_procedures', models.ManyToManyField(blank=True, help_text='Procedures operators should follow for recovery', related_name='fdir_entries', to='procedures.procedure')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fdir_entries', to='fdir.subsystem')),
            ],
            options={
                'verbose_name': 'FDIR entry',
                'verbose_name_plural': 'FDIR entries',
                'ordering': ['subsystem__name', 'name'],
                'indexes': [models.Index(fields=['subsystem'], name='fdir_fdiren_subsyst_5d0a57_idx'), models.Index(fields=['severity'], name='fdir_fdiren_severit_c6c200_idx')],
            },
        ),
    ]
