# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for UI badge (e.g. #3B82F6)', max_length=7)),
                ('is_sandbox', models.BooleanField(default=False, help_text='Sandbox missions are for testing and training.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MissionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('OPERATOR', 'Operator'), ('ADMIN', 'Admin')], default='OPERATOR', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mission', 'user'],
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
