# Generated by Django 4.2.29 on 2026-03-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handbook_subsystems', to='missions.mission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=120)),
                ('mnemonic', models.CharField(blank=True, help_text='Telemetry mnemonic or short code (e.g. BAT_TEMP, V_BUS)', max_length=80)),
                ('mnemonic_description', models.TextField(blank=True, help_text='Extended description of what this mnemonic is (e.g. engineering unit, where it appears in telemetry)')),
                ('user_notes', models.TextField(blank=True, help_text='Operator or team notes (e.g. observed behavior, fleet-specific notes)')),
                ('apids', models.CharField(blank=True, help_text='APID(s) this parameter can come down on (e.g. 0x0801, 0x0802 or HK, Science)', max_length=200)),
                ('description', models.TextField(help_text='Alert meaning and operational impact')),
                ('alert_conditions', models.TextField(blank=True, help_text='When/how the alert triggers')),
                ('warning_threshold', models.CharField(blank=True, max_length=80)),
                ('critical_threshold', models.CharField(blank=True, max_length=80)),
                ('recommended_response', models.TextField(blank=True, help_text='Operator actions or procedure reference')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_definitions', to='missions.mission')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_alerts', to='procedures.procedure')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_definitions', to='handbook.subsystem')),
            ],
            options={
                'ordering': ['subsystem__name', 'parameter'],
                'indexes': [models.Index(fields=['subsystem'], name='handbook_al_subsyst_8a6161_idx'), models.Index(fields=['parameter'], name='handbook_al_paramet_672a52_idx'), models.Index(fields=['severity'], name='handbook_al_severit_ea0a5d_idx')],
            },
        ),
    ]
