# Generated by Django 6.0.3 on 2026-03-06 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0003_add_run_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='Alert meaning and operational impact')),
                ('alert_conditions', models.TextField(blank=True, help_text='When/how the alert triggers')),
                ('warning_threshold', models.CharField(blank=True, max_length=80)),
                ('critical_threshold', models.CharField(blank=True, max_length=80)),
                ('recommended_response', models.TextField(blank=True, help_text='Operator actions or procedure reference')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_alerts', to='procedures.procedure')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_definitions', to='handbook.subsystem')),
            ],
            options={
                'ordering': ['subsystem__name', 'parameter'],
                'indexes': [models.Index(fields=['subsystem'], name='handbook_al_subsyst_8a6161_idx'), models.Index(fields=['parameter'], name='handbook_al_paramet_672a52_idx'), models.Index(fields=['severity'], name='handbook_al_severit_ea0a5d_idx')],
            },
        ),
    ]
