# Generated by Django 6.0.3 on 2026-03-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdefinition',
            name='apids',
            field=models.CharField(blank=True, help_text='APID(s) this parameter can come down on (e.g. 0x0801, 0x0802 or HK, Science)', max_length=200),
        ),
        migrations.AddField(
            model_name='alertdefinition',
            name='mnemonic',
            field=models.CharField(blank=True, help_text='Telemetry mnemonic or short code (e.g. BAT_TEMP, V_BUS)', max_length=80),
        ),
    ]
