# Generated by Django 6.0.3 on 2026-03-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_add_mnemonic_apids'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdefinition',
            name='mnemonic_description',
            field=models.TextField(blank=True, help_text='Extended description of what this mnemonic is (e.g. engineering unit, where it appears in telemetry)'),
        ),
        migrations.AddField(
            model_name='alertdefinition',
            name='user_notes',
            field=models.TextField(blank=True, help_text='Operator or team notes (e.g. observed behavior, fleet-specific notes)'),
        ),
    ]
