# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('handbook', '0003_add_mnemonic_description_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdefinition',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_definitions', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handbook_subsystems', to='missions.mission'),
        ),
    ]
