# Generated by Django 6.0.3 on 2026-03-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label (e.g. Pass complete, Contact logged)', max_length=120)),
                ('default_description', models.TextField(blank=True, help_text='Pre-filled description; user can edit before saving.')),
                ('default_severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = first in list.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_templates', to='scribe.eventcategory')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_templates', to='scribe.role')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
