# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('scribe', '0002_add_entry_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrytemplate',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_templates', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionlogentry',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_log_entries', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='role',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scribe_roles', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='scribetag',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scribe_tags', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='shift',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='scribetag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scribetag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
