# Generated by Django 4.2.29 on 2026-03-07 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0004_add_procedure_description'),
        ('anomalies', '0003_add_resolution_procedure'),
        ('scribe', '0002_add_entry_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMERequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CLARIFICATION', 'Needs Clarification'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('description', models.TextField(help_text='Describe the data or analysis being requested.')),
                ('time_range_start', models.DateTimeField(blank=True, help_text='Start of the time range for requested data.', null=True)),
                ('time_range_end', models.DateTimeField(blank=True, help_text='End of the time range for requested data.', null=True)),
                ('result_notes', models.TextField(blank=True, help_text='Output or results delivered for this request.')),
                ('rejection_reason', models.TextField(blank=True, help_text='Explanation if request was rejected or needs clarification.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('linked_event', models.ForeignKey(blank=True, help_text='Optionally link to an operational event from Mission Scribe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_requests', to='scribe.missionlogentry')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_requests', to='smerequests.requesttype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_requests_created', to=settings.AUTH_USER_MODEL)),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_requests', to='procedures.satellite')),
                ('subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_requests', to='anomalies.subsystem')),
            ],
            options={
                'verbose_name': 'SME request',
                'verbose_name_plural': 'SME requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_request_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='smerequests.smerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
