# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('smerequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_types', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='smerequest',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_requests', to='missions.mission'),
        ),
    ]
