# Generated by Django 6.0.3 on 2026-03-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='procedures.procedurerun'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='procedures', to='procedures.tag'),
        ),
    ]
