# Generated by Django 6.0.3 on 2026-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_tag_alter_stepexecution_run_procedure_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurerun',
            name='run_notes',
            field=models.TextField(blank=True, help_text='Handover or anomaly notes for this run.'),
        ),
    ]
