# Generated by Django 4.2.29 on 2026-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_add_run_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(blank=True, default='', help_text='High-level description of what this procedure accomplishes.'),
        ),
    ]
