# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('procedures', '0005_subsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='procedurerun',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_runs', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='subsystem',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='tag',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
