# Generated by Django 4.2.29 on 2026-03-10 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0001_initial'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('L1', 'L1 — Informational'), ('L2', 'L2 — Minor'), ('L3', 'L3 — Operational'), ('L4', 'L4 — Major'), ('L5', 'L5 — Critical')], default='L2', max_length=5)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('MITIGATED', 'Mitigated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('detected_time', models.DateTimeField()),
                ('root_cause', models.TextField(blank=True, help_text='Root cause summary documented at resolution.')),
                ('resolution_actions', models.TextField(blank=True, help_text='Actions taken to resolve the issue.')),
                ('recommendations', models.TextField(blank=True, help_text='Follow-up recommendations or lessons learned.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_anomalies', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='missions.mission')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='procedures.satellite')),
                ('subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='procedures.subsystem')),
            ],
            options={
                'verbose_name_plural': 'anomalies',
                'ordering': ['-detected_time'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('NOTE', 'Note'), ('STATUS_CHANGE', 'Status Change'), ('SEVERITY_CHANGE', 'Severity Change'), ('ACTION', 'Action Taken'), ('PROCEDURE', 'Procedure Run')], default='NOTE', max_length=20)),
                ('body', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=50)),
                ('new_value', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='anomalies.anomaly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'anomaly timeline entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
