# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_add_run_notes'),
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='procedure_run',
            field=models.ForeignKey(
                blank=True,
                help_text='If this anomaly was observed during a procedure run, link it here.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='linked_anomalies',
                to='procedures.procedurerun',
            ),
        ),
    ]
