# Generated by Django 4.2.29 on 2026-03-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='operational_impact',
            field=models.CharField(blank=True, default='', help_text='Short description of operational impact (e.g. None, Low, Mission delay).', max_length=100),
        ),
    ]
