# Generated by Django 6.0.3 on 2026-03-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0002_anomaly_procedure_run'),
        ('procedures', '0003_add_run_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='resolution_procedure',
            field=models.ForeignKey(blank=True, help_text='Procedure used or recommended to resolve this anomaly (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_for_anomalies', to='procedures.procedure'),
        ),
    ]
