# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('anomalies', '0003_rename_columns_to_match_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='missions.mission'),
        ),
    ]
