# Generated by Django 4.2.29 on 2026-03-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('command_id', models.CharField(blank=True, help_text='Command opcode or numeric identifier', max_length=80)),
                ('subsystem', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='Command group or category', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_definitions', to='missions.mission')),
            ],
            options={
                'ordering': ['subsystem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mnemonic', models.CharField(blank=True, max_length=120)),
                ('apid', models.CharField(blank=True, help_text='APID or packet reference', max_length=120)),
                ('subsystem', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(blank=True, max_length=80)),
                ('units', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_definitions', to='missions.mission')),
            ],
            options={
                'ordering': ['subsystem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommandInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Position of this input in the command argument list')),
                ('data_type', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('constraints', models.TextField(blank=True, help_text='Valid ranges, enums, or other constraints')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='cmdtlm.commanddefinition')),
            ],
            options={
                'ordering': ['command', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Raw numeric or coded value', max_length=80)),
                ('label', models.CharField(help_text='Human-readable meaning', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enums', to='cmdtlm.telemetrydefinition')),
            ],
            options={
                'ordering': ['telemetry', 'value'],
                'indexes': [models.Index(fields=['telemetry'], name='cmdtlm_tele_telemet_694a41_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='telemetrydefinition',
            index=models.Index(fields=['subsystem'], name='cmdtlm_tele_subsyst_309281_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydefinition',
            index=models.Index(fields=['name'], name='cmdtlm_tele_name_17355b_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydefinition',
            index=models.Index(fields=['mnemonic'], name='cmdtlm_tele_mnemoni_d8f2de_idx'),
        ),
        migrations.AddIndex(
            model_name='commandinput',
            index=models.Index(fields=['command'], name='cmdtlm_comm_command_1288b8_idx'),
        ),
        migrations.AddIndex(
            model_name='commanddefinition',
            index=models.Index(fields=['subsystem'], name='cmdtlm_comm_subsyst_0a4293_idx'),
        ),
        migrations.AddIndex(
            model_name='commanddefinition',
            index=models.Index(fields=['name'], name='cmdtlm_comm_name_643553_idx'),
        ),
        migrations.AddIndex(
            model_name='commanddefinition',
            index=models.Index(fields=['command_id'], name='cmdtlm_comm_command_b1e5d5_idx'),
        ),
    ]
