# Generated by Django 4.2.29 on 2026-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('cmdtlm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanddefinition',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_definitions', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='telemetrydefinition',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_definitions', to='missions.mission'),
        ),
    ]
