# Generated by Django 4.2.29 on 2026-03-08 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RUN_START', 'Run Started'), ('RUN_COMPLETE', 'Run Completed'), ('RUN_ABORT', 'Run Aborted'), ('STATUS_CHANGE', 'Status Change'), ('IMPORT', 'CSV Import'), ('EXPORT', 'CSV Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('model_name', models.CharField(help_text='e.g. Procedure, Anomaly, AlertDefinition', max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, help_text='Human-readable representation at time of action', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Additional context: changed fields, notes, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='missions.mission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mission', '-timestamp'], name='auditlog_au_mission_9593e8_idx'), models.Index(fields=['user', '-timestamp'], name='auditlog_au_user_id_feb285_idx'), models.Index(fields=['action'], name='auditlog_au_action_b10cac_idx'), models.Index(fields=['model_name'], name='auditlog_au_model_n_1b93bf_idx')],
            },
        ),
    ]
